export const DETALLE_ASESOR_EXAM_TYPES = [
    "Pre-A1 Starters",
    "A1 Movers",
    "A2 Flyers",
    "A2 Key",
    "A2 Key for Schools",
    "B1 Preliminary",
    "B1 Preliminary for Schools",
    "B2 First",
    "B2 First for Schools",
    "C1 Advanced",
    "C2 Proficiency",
    "Linguaskill",
    "TKT",
    "Delta",
    "CELTA",
    "IELTS",
    "MET",
    "MET Go!",
    "TEA",
    "Other",
] as const


export const EXAM_TYPE_LABELS = [
    "STA",
    "MOV",
    "FLY",
    "KET",
    "KETfs",
    "PET",
    "PETfs",
    "FCE",
    "FCEfs",
    "CAE",
    "CPE",
    "Linguaskill",
    "TKT",
    "Delta",
    "CELTA",
    "IELTS",
    "MET",
    "MET Go!",
    "TEA",
    "Other",
] as const
